version: "3.8"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/src/node_modules
      - .:/app/src
    env_file:
      - ./.env